# My Jupyter Notebook on IBM Watson Studio 

## Hafez Ibrahim
## Lecturer

 *I am interested in data science because I love to work with data and Algorithms*

### The Follwing code explain how to change  the array from vector to matrix

In [2]:
import numpy as np

In [4]:
a=np.arange(20).reshape(4,5)

In [5]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


<a href="https://iua.edu.sd/"> International University of Africa</a>

|Col1|col2|
|----|----|
|cel1|cel2|

- one
- two